# Generated by Django 5.1.4 on 2026-06-04 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armazens', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filial')),
            ],
            options={
                'verbose_name': 'Armazém',
                'verbose_name_plural': 'Armazéns',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corredores', to='wms.armazem')),
            ],
            options={
                'verbose_name': 'Corredor',
                'ordering': ['codigo'],
                'unique_together': {('armazem', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='wms.corredor')),
            ],
            options={
                'verbose_name': 'Bay',
                'ordering': ['numero'],
                'unique_together': {('corredor', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='EntradaMercadoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_nf', models.CharField(max_length=50)),
                ('fornecedor', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('divergencia', 'Divergência')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('chegada_em', models.DateTimeField()),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='wms.armazem')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Mercadoria',
                'verbose_name_plural': 'Entradas de Mercadoria',
                'ordering': ['-chegada_em'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis', to='wms.bay')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
                'ordering': ['numero'],
                'unique_together': {('bay', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nivel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posicao', to='wms.nivel')),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('unidade', models.CharField(default='un', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'ordering': ['descricao'],
                'unique_together': {('empresa', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ItemEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_esperada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade_conferida', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='wms.entradamercadoria')),
                ('posicao', models.ForeignKey(blank=True, help_text='Posição onde o item será armazenado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_entrada', to='wms.posicao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_entrada', to='wms.produto')),
            ],
            options={
                'verbose_name': 'Item de Entrada',
                'verbose_name_plural': 'Itens de Entrada',
            },
        ),
        migrations.CreateModel(
            name='SaidaMercadoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(blank=True, max_length=50)),
                ('destinatario', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_separacao', 'Em separação'), ('separado', 'Separado'), ('expedido', 'Expedido')], default='pendente', max_length=20)),
                ('expedida_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='wms.armazem')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saída de Mercadoria',
                'verbose_name_plural': 'Saídas de Mercadoria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste de inventário'), ('transferencia', 'Transferência')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origem_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='wms.entradamercadoria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='wms.posicao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='wms.produto')),
                ('origem_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='wms.saidamercadoria')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ItemSaida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_saida', to='wms.posicao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wms.produto')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='wms.saidamercadoria')),
            ],
            options={
                'verbose_name': 'Item de Saída',
            },
        ),
    ]
