# Generated by Django 5.1.4 on 2026-06-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armazem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
