# Generated by Django 5.1.4 on 2026-06-08 01:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('segmento', models.CharField(choices=[('industria', 'Indústria'), ('varejo', 'Varejo'), ('distribuicao', 'Distribuição'), ('ecommerce', 'E-commerce'), ('agronegocio', 'Agronegócio'), ('saude', 'Saúde'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], default='lead', max_length=20)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('site', models.URLField(blank=True)),
                ('email_principal', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_crm', to='core.empresa')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Consultor/vendedor responsável pelo cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razao_social'],
                'unique_together': {('empresa', 'cnpj')},
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('decisor', models.BooleanField(default=False, help_text='Indica se esta pessoa tem poder de decisão sobre contratos')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-decisor', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('servico', models.CharField(choices=[('armazenagem', 'Armazenagem'), ('frete', 'Frete'), ('ambos', 'Armazenagem + Frete')], default='ambos', max_length=20)),
                ('valor_mensal', models.DecimalField(decimal_places=2, help_text='Valor mensal do contrato (R$)', max_digits=12)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, help_text='Deixar em branco para contrato por prazo indeterminado', null=True)),
                ('sla_prazo_entrega_horas', models.PositiveSmallIntegerField(default=48, help_text='Prazo máximo de entrega acordado em horas')),
                ('objeto', models.TextField(blank=True, help_text='Descrição do objeto do contrato')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='crm.cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-vigencia_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('servico', models.CharField(choices=[('armazenagem', 'Armazenagem'), ('frete', 'Frete'), ('ambos', 'Armazenagem + Frete')], default='frete', max_length=20)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mensal estimado do contrato (R$)', max_digits=12, null=True)),
                ('etapa', models.CharField(choices=[('prospeccao', 'Prospecção'), ('qualificacao', 'Qualificação'), ('proposta', 'Proposta enviada'), ('negociacao', 'Em negociação'), ('fechado_ganho', 'Fechado — ganho'), ('fechado_perdido', 'Fechado — perdido')], default='prospeccao', max_length=20)),
                ('probabilidade', models.PositiveSmallIntegerField(default=10, help_text='Probabilidade de fechamento (0-100%)')),
                ('previsao_fechamento', models.DateField(blank=True, null=True)),
                ('motivo_perda', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.cliente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoInteracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação telefônica'), ('email', 'E-mail'), ('reuniao', 'Reunião'), ('visita', 'Visita presencial'), ('proposta', 'Envio de proposta'), ('outro', 'Outro')], max_length=20)),
                ('resumo', models.TextField()),
                ('data_interacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='crm.cliente')),
                ('contato', models.ForeignKey(blank=True, help_text='Contato com quem a interação foi realizada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='crm.contato')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_registradas', to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(blank=True, help_text='Oportunidade relacionada à interação (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Histórico de Interação',
                'verbose_name_plural': 'Histórico de Interações',
                'ordering': ['-data_interacao'],
                'default_permissions': ('add', 'view'),
            },
        ),
    ]
