# Generated by Django 5.1.4 on 2026-06-07 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('wms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRomaneio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatario', models.CharField(max_length=255)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero_end', models.CharField(blank=True, max_length=20)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ordem_entrega', models.PositiveSmallIntegerField(default=0, help_text='Ordem de parada na rota (0 = não definida)')),
                ('status_entrega', models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('tentativa', 'Tentativa sem sucesso'), ('devolvido', 'Devolvido')], default='pendente', max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saida_wms', models.ForeignKey(blank=True, help_text='Saída de mercadoria correspondente no WMS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_romaneio', to='wms.saidamercadoria')),
            ],
            options={
                'verbose_name': 'Item de Romaneio',
                'verbose_name_plural': 'Itens de Romaneio',
                'ordering': ['romaneio', 'ordem_entrega'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('cnh', models.CharField(max_length=20)),
                ('categoria_cnh', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='B', max_length=5)),
                ('validade_cnh', models.DateField()),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motoristas', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome_completo'],
                'unique_together': {('empresa', 'cpf')},
            },
        ),
        migrations.CreateModel(
            name='POD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assinado_por', models.CharField(blank=True, help_text='Nome de quem recebeu a mercadoria', max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, help_text='GPS no momento da entrega', null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='tms.itemromaneio')),
            ],
            options={
                'verbose_name': 'Comprovante de Entrega (POD)',
                'verbose_name_plural': 'Comprovantes de Entrega (POD)',
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Romaneio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, help_text='Número sequencial do romaneio (pode ser gerado automaticamente)', max_length=50)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_rota', 'Em rota'), ('concluido', 'Concluído'), ('com_ocorrencia', 'Com ocorrência'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('data_saida_prevista', models.DateTimeField(blank=True, null=True)),
                ('data_saida_real', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='romaneios', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filial')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios', to='tms.motorista')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Romaneio',
                'verbose_name_plural': 'Romaneios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('avaria', 'Avaria / dano'), ('atraso', 'Atraso'), ('tentativa', 'Tentativa de entrega sem sucesso'), ('roubo', 'Roubo / furto'), ('acidente', 'Acidente'), ('recusa', 'Recusa do destinatário'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, help_text='Item específico ao qual a ocorrência se refere (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='tms.itemromaneio')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='tms.romaneio')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itemromaneio',
            name='romaneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='tms.romaneio'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('proprio', 'Próprio'), ('terceiro', 'Terceirizado'), ('moto', 'Moto'), ('furgao', 'Furgão'), ('caminhao', 'Caminhão')], default='proprio', max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('capacidade_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade de carga em quilogramas', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_rota', 'Em rota'), ('manutencao', 'Em manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
                'unique_together': {('empresa', 'placa')},
            },
        ),
        migrations.AddField(
            model_name='romaneio',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios', to='tms.veiculo'),
        ),
    ]
