# Generated by Django 5.1.4 on 2026-06-08 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemromaneio',
            name='cliente_crm',
            field=models.ForeignKey(blank=True, help_text='Cliente CRM destinatário desta entrega (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_romaneio', to='crm.cliente'),
        ),
    ]
